### ISSUE TITLE
joinmarket capitalization

### ISSUE THREAD

**Issue by ghost** [joinmarket-webui/jamdocs#1]
I believe the "official" spelling is all in lower case, unless it's the beginning of a sentence, so "joinmarket" or "Joinmarket".

**Comment by dergigi** [comment]
Ah, well, turns out there is no consistency in the "official" docs. All kinds of variations are present:

- [JoinMarket](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/f1d0014375defa715c1504b57c5b4481dceec101/README.md?plain=1#L5)
- [Joinmarket](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/88b5e6a8eee6e75b4b838594d4cad1a4b949d32a/docs/TESTING.md?plain=1#L3)
- [joinmarket](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/2da075c3d8e00a60bd532db5f7bddde62bb9ffee/docs/YIELDGENERATOR.md?plain=1#L9)

I changed it to `Joinmarket` in commit 256dbc3a0d4d614f82c77f10701d9ab8b509d5f2, but, according to this [twitter poll](https://twitter.com/dergigi/status/1549722048024481794?s=20&t=KXs8Qu4A_jmhATv6KlOg6A) most people like `JoinMarket` more, so I changed it back with dd5c9c9ed87ee840ddd5e69929a5843704a9c1a8.

> _In this house, we respect the laws of CamelCase spelling!_

Closing issue.
